### ISSUE TITLE
Trying to use the plugin with limited success

### ISSUE THREAD

**Issue by andreialecu** [bgotink/yarn-plugin-angular#1]
Hey @bgotink, thanks for the work here! Randomly found this and I'm hoping that it can help in getting unblocked. Unfortunately there are not many resources on running Angular on PnP.

I'm currently working on migrating a workspace that contains an Angular project to PnP. I've been trying `pnpify` and your plugin, but cannot seem to get things to work. 😞 

With `node_modules` everything runs correctly. I've added a ton of `packageExtensions` to deal with missing dependencies, and those errors are out of the way. However, now even more angular compiler errors have popped up. So many in fact that I had to bump the terminal buffer length to 50000 lines just to be able to see the first error.

Most of the errors are that basically no pipe or property can be resolved on any element:

```
Can't bind to 'ngModel' since it isn't a known property of 'input'.

27         <input type="text" tabindex="3" [(ngModel)]="input" autofocus required pattern="{{format || '(.*)' }}" name="input" #myInput="" autocomplete="off">{{ myInput.focus() }}
                                           ~~~~~~~~~~~~~~~~~~~
```
```
error NG8002: Can't bind to 'debounce' since it isn't a known property of 'angular-selector'
```

The first few errors are:

```
ERROR in ../../.yarn/$$virtual/ngx-moment-virtual-11e429ae6e/0/cache/ngx-moment-npm-3.5.0-35df4d5b24-8f41696744.zip/node_modules/ngx-moment/moment.module.d.ts:4:49 - error NG6005: MomentModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

4     static forRoot(options?: NgxMomentOptions): ModuleWithProviders;
                                                  ~~~~~~~~~~~~~~~~~~~
../../.yarn/$$virtual/@angular-material-virtual-42d7ec537b/0/cache/@angular-material-npm-8.2.3-6a72a9daf2-b9c05fb72c.zip/node_modules/@angular/material/tabs/typings/tabs-module.d.ts:8:22 - error NG6003: Appears in the NgModule.exports of RouterTabModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/material) which declares MatTabsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

One thing I noticed was that on `node_modules` the compiler would compile each module separately, so lines like:

```
Compiling @angular/core
Compiling @angular/common
```

Would be printed at startup. It seems this does not happen on PnP, and it may be the reason for the errors.

Do you have any pointers on what could be wrong? Also, I'm not sure if you use the Yarn discord any more, might be easier to explain it there if you did.

I've also been trying to move the PnP story further for Angular, eg: https://github.com/angular/angular-cli/pull/18610 and I'm hopeful that I might be able to lend a hand here as well.

**Comment by bgotink** [comment]
HI @andreialecu! I've only got one repository running angular with PnP and it's actually a repo full of Angular CLI extensions (own schematics and a homebrewed library packager we use instead of ng-packagr) with a couple of angular applications with different versions set up as e2e test of those builders, so mostly empty apps.

For all other angular repositories I'm using the node-modules linker because it just works, contrary to using PnP.

There are some open issues at angular's side that I've been able to work around via this plugin, but it still requires a lot of work. https://github.com/angular/angular/issues/38099 requires all packages used at runtime (when using the ivy renderer) to be unplugged, which is a pain. The Angular CLI has some smaller issues, though the fact that they now include the pnp webpack plugin already solves a lot!

Anyhow, back on topic. It's hard to see what exactly is going wrong, but at first glance it seems like `ngx-moment` version 3.5.0 is incompatible with angualr 10 (https://github.com/urish/ngx-moment/commit/4d899d0a6d829c26b259b5104ddb54e11e4c8282) and your dependencies (`@angular/material`, &hellip;) need to be unplugged. Without unplugging, `ngcc` fails to upgrade the packages from Renderer2 to Ivy and things break down.

Especially the unplugging makes a big benefit of PnP disappear. Suddenly you're back to needing to run yarn installs every time a dependency changes.
Until that's fixed on Angular's side, I'm not going to spend much time on keeping this plugin's PnP support going.

**Comment by andreialecu** [comment]
Hey, thanks for answering! There has been an update in that thread you linked earlier today, and work is underway to actually support PnP natively in Angular as part of those changes. See https://github.com/angular/angular/issues/38366 and https://github.com/orgs/angular/projects/2

However, I have a bigger workspace which I just migrated to PnP, but the Angular project in it isn't working.

The errors above are not related to the angular version or anything of that matter, because the exact same project works fine with the `node_modules` linker. However, because it's part of a monorepo I'm forced to try to use PnP for it.

I'm going to try to experiment with unplugging some more, but the one thing I noticed that is different is that when running `ng serve` using pnpify or your plugin, none of the 

```
Compiling @angular/core
Compiling @angular/common
```

Messages appear. I was wondering if you have any clue why that may be. I think it's the root cause of the issue.

**Comment by andreialecu** [comment]
After unplugging some additional packages, it seems a new single error appeared:

```
ERROR in The target entry-point "@angular/platform-browser-dynamic" has missing dependencies:
 - @angular/compiler
 - @angular/core
 - @angular/common
 - @angular/platform-browser
```

I'm not sure what it means though, all those packages exist and are in the angular project's `package.json`. I'm using Angular 9.1.12 if it matters. (all are on the same version too)

When using just `pnpify` the error changes a little bit:

```
ERROR in The target entry-point "@angular/platform-browser-dynamic" has missing dependencies:
 - @angular/core
 - @angular/common
 - @angular/platform-browser
```

I wonder if this might be triggered by using yarn workspaces (monorepo) instead of being a single repo.

Sorry to hijack this, it seems that you're the only person that has had success with angular and pnp.

**Comment by andreialecu** [comment]
Alright, I guess I'll just set up a separate `node_modules` repo for the angular workspace, and publish its dependent packages on something like Github Packages in the meantime until full Angular PnP support is resolved.

Will be tracking https://github.com/orgs/angular/projects/2

Seems that besides very simple/empty apps, `pnpify` won't really work with a real world app.

**Comment by bgotink** [comment]
I haven't used angular 9 at all to be honest, we've skipped it and went straight for angular 10. That might explain why I never ran into these issues, I have literally never used angular 9 on PnP.

`pnpify` patches the node filesystem so it appears that the `node_modules` folders exist, but in fact it's really just PnP. This works for things that misbehave by e.g. trying to list all packages in `node_modules` but it doesn't help at all with the things angular is doing: writing to packages in the `node_modules` folder.
