### ISSUE TITLE
ng serve may be broken?

### ISSUE THREAD

**Issue by rhefner** [bgotink/yarn-plugin-angular#2]
Hi there! This is an awesome effort. :)

I am (seemingly) one of the few that has issues with getting Angular to work appropriately with `nodeLinker: node-modules` because it seems to collide with my other projects, no matter what hoisting strategy I use for the workspace. Since every other project in my monorepo works fine with PnP, it's hard to justify going back to `node-modules` just for one project ... So, I'm trying to figure out alternate ways of getting Angular to work with PnP and this is closer than most of what I've tried.

I _think_ that `serve` is broken / not working, at least with Angular 11 (11.0.2). I read the last comment and it seems that you may not be using it? If you are, maybe my usage is wrong. `yarn workspace @monorepo/angular g:run:ng g ...` works, but `yarn workspace @monorepo/angular g:run:ng serve` fails with:

```
[error] Error: Cannot locate the 'node_modules' directory.
    at NgccProcessor.findNodeModulesDirectory (/path/to/my/monorepo/.yarn/$$virtual/@ngtools-webpack-virtual-9e6973a19c/0/cache/@ngtools-webpack-patch-6b7522a4b5-363414fda9.zip/node_modules/@ngtools/webpack/src/ngcc_processor.js:208:15)
    at new NgccProcessor (/path/to/my/monorepo/.yarn/$$virtual/@ngtools-webpack-virtual-9e6973a19c/0/cache/@ngtools-webpack-patch-6b7522a4b5-363414fda9.zip/node_modules/@ngtools/webpack/src/ngcc_processor.js:36:43)
    at /path/to/my/monorepo/.yarn/$$virtual/@ngtools-webpack-virtual-9e6973a19c/0/cache/@ngtools-webpack-patch-6b7522a4b5-363414fda9.zip/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:592:33
    at SyncHook.eval [as call] (eval at create (/path/to/my/monorepo/.yarn/cache/tapable-npm-1.1.3-56489411a8-b2c2ab2026.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/path/to/my/monorepo/.yarn/cache/tapable-npm-1.1.3-56489411a8-b2c2ab2026.zip/node_modules/tapable/lib/Hook.js:154:20)
    at Object.webpack [as webpackFactory] (/path/to/my/monorepo/.yarn/$$virtual/webpack-virtual-c112ce844b/0/cache/webpack-npm-4.44.2-eedc4b763e-cb4a9051d6.zip/node_modules/webpack/lib/webpack.js:55:30)
    at createWebpack (/path/to/my/monorepo/.yarn/$$virtual/@angular-devkit-build-webpack-virtual-a420a3543f/0/cache/@angular-devkit-build-webpack-npm-0.1100.2-013e9fb697-7d041c4856.zip/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js:21:36)
    at Object.runWebpackDevServer (/path/to/my/monorepo/.yarn/$$virtual/@angular-devkit-build-webpack-virtual-a420a3543f/0/cache/@angular-devkit-build-webpack-npm-0.1100.2-013e9fb697-7d041c4856.zip/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js:47:12)
    at SwitchMapSubscriber.project (/path/to/my/monorepo/.yarn/$$virtual/@angular-devkit-build-angular-virtual-5321fb971f/0/cache/@angular-devkit-build-angular-patch-c1b6a2c51b-d16c6e5a66.zip/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:202:32)
    at SwitchMapSubscriber._next (/path/to/my/monorepo/.yarn/cache/rxjs-npm-6.6.3-a1e67d677b-61a3da6db9.zip/node_modules/rxjs/internal/operators/switchMap.js:47:27)
```

`g:run:ng` in my monorepo root's `package.json` has `g:run:ng` as this:

```
"scripts": {
    ...
    "g:run:ng": "cd $INIT_CWD && yarn ng"
    ...
  },
```

It doesn't look like the patch [here](https://github.com/bgotink/yarn-plugin-angular/blob/latest/patches/%40ngtools/webpack.patch) applies to `NgccProcessor.findNodeModulesDirectory` in [@ngtools/webpack/src/ngcc_processor.js](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/ngcc_processor.ts) .. Is this necessary to patch as well for 'serve' to function correctly?

Thank you!

**Comment by bgotink** [comment]
Thanks for noticing!
I've only got one repo using PnP with Angular atm, because ivy and PnP don't cooperate that well. I've looked into it, patched a couple of angular files and now it should work!

**Comment by rhefner** [comment]
Thanks, @bgotink! I just tried it out and, while it installs fine, it's having trouble after running `yarn`:

```
➤ YN0000: └ Completed in 0s 434ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @angular/compiler-cli@patch:@angular/compiler-cli@npm%3A11.0.2#builtin<ng/@angular/compiler-cli>::version=11.0.2&hash=9c1f82 can't be found in the cache and will be f
➤ YN0013: │ @ngtools/webpack@patch:@ngtools/webpack@npm%3A11.0.2#builtin<ng/@ngtools/webpack>::version=11.0.2&hash=be8658 can't be found in the cache and will be fetched from the
➤ YN0066: │ @ngtools/webpack@patch:@ngtools/webpack@npm%3A11.0.2#builtin<ng/@ngtools/webpack>::version=11.0.2&hash=be8658: Cannot apply hunk #1 (set enableInlineHunks for details)
```

May be my problem and haven't looked into it fully yet, but thought I would let you know. :)

**Comment by rhefner** [comment]
With `enableInlineHunks`:

```
➤ YN0000: └ Completed in 0s 433ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ @angular/compiler-cli@patch:@angular/compiler-cli@npm%3A11.0.2#builtin<ng/@angular/compiler-cli>::version=11.0.2&hash=9c1f82 can't be found in the cache and will be f
➤ YN0013: │ @ngtools/webpack@patch:@ngtools/webpack@npm%3A11.0.2#builtin<ng/@ngtools/webpack>::version=11.0.2&hash=be8658 can't be found in the cache and will be fetched from the
➤ YN0066: │ @ngtools/webpack@patch:@ngtools/webpack@npm%3A11.0.2#builtin<ng/@ngtools/webpack>::version=11.0.2&hash=be8658: Cannot apply hunk #1
➤ YN0000: │           this.tsConfigPath = tsConfigPath;
➤ YN0000: │           this._processedModules = new Set();
➤ YN0000: │           this._logger = new NgccLogger(this.compilationWarnings, this.compilationErrors);
➤ YN0028: │ -         this._nodeModulesDirectory = this.findNodeModulesDirectory(this.basePath);
➤ YN0028: │ +         this._nodeModulesDirectory = require('path').join(__dirname.slice(0, __dirname.lastIndexOf('/.yarn/')), 'node_modules');// this.findNodeModulesDirectory(this.basePath);
➤ YN0000: │       }
➤ YN0000: │       /** Process the entire node modules tree. */
➤ YN0000: │       process() {
➤ YN0028: │ +         return;
➤ YN0000: │           // Under Bazel when running in sandbox mode parts of the filesystem is read-only.
➤ YN0000: │           if (process.env.BAZEL_TARGET) {
➤ YN0000: │               return;
➤ YN0000: │           }
➤ YN0000: └ Completed in 1s 47ms
```

**Comment by rhefner** [comment]
Looking at this a little more closely - I reproduced the issue checking out the repo and building manually, which had the same issue. The patch diff had `semver exclusivity ^11` in between the `diff --git` and `---/+++` stanzas in the patch which I thought was odd:
```
diff --git a/src/ngcc_processor.js b/src/ngcc_processor.js
semver exclusivity ^11
--- a/src/ngcc_processor.js
+++ b/src/ngcc_processor.js
@@ -31,11 +31,12 @@ class NgccProcessor {
         this.tsConfigPath = tsConfigPath;
         this._processedModules = new Set();
         this._logger = new NgccLogger(this.compilationWarnings, this.compilationErrors);
-        this._nodeModulesDirectory = this.findNodeModulesDirectory(this.basePath);
+        this._nodeModulesDirectory = require('path').join(__dirname.slice(0, __dirname.lastIndexOf('/.yarn/')), 'node_modules');// this.findNodeModulesDirectory(this.basePath);
     }
     /** Process the entire node modules tree. */
     process() {
+        return;
         // Under Bazel when running in sandbox mode parts of the filesystem is read-only.
         if (process.env.BAZEL_TARGET) {
             return;
         }
```
I `yarn patch @ngtools/webpack`'ed my version, generated a similar patch and applied it to `patches/@ngtools/webpack.patch` in this repo and ran:
```
yarn generate-patches
git add .
yarn version 0.1.2
```
Then removed the older and installed locally without issue:
```
yarn plugin import ../yarn-plugin-angular/bin/@yarnpkg/plugin-angular.js
yarn
```

I don't know the exact workflow you're using, so I took an _educated_ guess. :-P With all that, running `ng serve` gets closer to working!

```
# yarn ng serve
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
See https://webpack.js.org/guides/hot-module-replacement for information on working with HMR for Webpack.
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
main.js               | main          |   2.16 MB
styles.css, styles.js | styles        | 582.03 kB
polyfills.js          | polyfills     | 492.51 kB
runtime.js            | runtime       |  33.44 kB

                      | Initial Total |   3.24 MB

Build at: 2020-11-26T21:56:33.727Z - Hash: 3bf8dc6ceda9c09d594d - Time: 12700ms

Error: ../../.yarn/$$virtual/@angular-cdk-virtual-f783438b37/0/cache/@angular-cdk-npm-11.0.1-bf060f6d98-6ba4d36db1.zip/node_modules/@angular/cdk/a11y/focus-monitor/focus-monitor.d.ts:10:28 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

10 import { Observable } from 'rxjs';
                              ~~~~~~
../../.yarn/$$virtual/@angular-cdk-virtual-f783438b37/0/cache/@angular-cdk-npm-11.0.1-bf060f6d98-6ba4d36db1.zip/node_modules/@angular/cdk/a11y/key-manager/list-key-manager.d.ts:9:25 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

9 import { Subject } from 'rxjs';
                          ~~~~~~
../../.yarn/$$virtual/@angular-cdk-virtual-f783438b37/0/cache/@angular-cdk-npm-11.0.1-bf060f6d98-6ba4d36db1.zip/node_modules/@angular/cdk/accordion/accordion.d.ts:10:25 - error TS2307: Cannot find module 'rxjs' or its corresponding type declarations.

10 import { Subject } from 'rxjs';
                           ~~~~~~
```

If that's the correct thing to do, I can submit a PR for the changes if you would like.

**Comment by bgotink** [comment]
> The patch diff had semver exclusivity ^11 in between the diff --git and ---/+++ stanzas in the patch which I thought was odd

Yeah, that's something yarn-specific. It allows for defining patches for different versions in a single file, where the package versions not inside the semver range don't get that specific patch. It's the method used by yarn to support multiple versions of typescript for instance.

Some changes were made to that file in 11.0.2 (https://github.com/angular/angular-cli/commit/4517f1a29c8d5c3d0a08ad243b4302c10baf214d), which explains why the patch no longer applies. I've got 11.0.1 in my PnP repo and I got `ng serve` up and running.

**Comment by rhefner** [comment]
Ah, I see! That would make sense. I was trying to find out which version of Angular you were using, but couldn't do so from this repo. :)

**Comment by bgotink** [comment]
Uh yeah this repo itself doesn't contain an angular workspace. I split this repo from another one that I can't share publicly, and I haven't gotten round to adding angular applications to allow testing the pluign in the plugin repo itself, I always jump back to my other repo for that.

> I don't know the exact workflow you're using, so I took an educated guess. :-P

Yeah I should probably add a "contributing" section with some information to the README. You've got it mostly right though! Just one remark: `yarn version` should be `yarn build` for testing, as the `version` script will create a commit and tag. Nothing you can't undo, but it's a little more work to undo those if you need to make further changes.

You're more than welcome to open a PR! I'd prefer to have both patches at the same time, so one should only be applied to `^11.0.2` and the other to `>= 11.0.0 < 11.0.2`.

**Comment by rhefner** [comment]
> Yeah, that's something yarn-specific. It allows for defining patches for different versions in a single file, where the package versions not inside the semver range don't get that specific patch. It's the method used by yarn to support multiple versions of typescript for instance.

This is good to know! I'll have to read up more on that, because at first glance it looked off to my untrained eye.

> Uh yeah this repo itself doesn't contain an angular workspace

:)

> Yeah I should probably add a "contributing" section with some information to the README. You've got it mostly right though! Just one remark: yarn version should be yarn build for testing, as the version script will create a commit and tag. Nothing you can't undo, but it's a little more work to undo those if you need to make further changes.

Got it -- Thank you for the info!

> You're more than welcome to open a PR! I'd prefer to have both patches at the same time, so one should only be applied to ^11.0.2 and the other to >= 11.0.0 < 11.0.2

Ok. I'm not sure how to keep both around for yarn ATM, but I will look into it. 👍

**Comment by rhefner** [comment]
BTW - I can confirm now after making appropriate fixes that Angular in my repo now works with PnP! I haven't looked at every little thing yet, but it seems 100%!
